name: photu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  photo_manager: ^3.6.0
  google_fonts: ^6.2.1
  photo_view: ^0.15.0
  permission_handler: ^12.0.0+1


flutter:

  uses-material-design: true
